services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - fullstack-net

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - fullstack-net
    depends_on:
      - backend

networks:
  fullstack-net:
